<?php
/**
* Generate PDF files from an HTML source (which itself is generated by PHP)
*
* Dependancies:
*		html2ps (linux utility)
*		ps2pdf (part of the ghostscript linux package)
*
* Refs:
*		http://user.it.uu.se/~jan/html2psug.html
*
* @package Ias
*/
namespace Buan;
use Buan\Config;

class PdfViewEngine extends PhpViewEngine implements IViewEngine {
	
	public $config = null;
	
	/**
	* Render the view and return the result as a PDF.
	* N.B. this transforms relative image paths into fully qualified ones
	*
	* @return string
	*/
	public function render() {

		// Render the PHP first to grab the HTML source
		$buffer = parent::render();
		
		// Transform relative image paths
		$fqdn = "http://" . Config::get('app.domain');
		
		// remove trailing slash - just in case
		if (substr($fqdn, -1) == '/') {
			$fqdn = substr($fqdn, 0, strlen($fqdn-1));
		}
		$buffer = preg_replace_callback(
			'/src=\"(.*?)\"/',
			function($match) use ($fqdn) {
				if (strpos($match[1], 'http') !== false)
					return $match[0];
				else
					return 'src="' . $fqdn . '/' . $match[1] . '"';
			},
			$buffer);
		
		
		// PDF Generation is not available on windows...
		if (stristr(PHP_OS, 'WIN')) {			
			return $buffer;
		}

		// Get command in path
		$cmd = exec('which wkhtmltopdf');

		$dir = dirname(Config::get('app.docRoot')) . '/pdfgen/temp/';
		$htmlname = $dir. uniqid() . ".html";
		$pdfname = $htmlname . ".pdf";

		file_put_contents($htmlname, $buffer);
		exec("$cmd -B 0 -L 0 -R 0 -T 0 -O Portrait $htmlname $pdfname >/dev/null 2>&1");
		$output = file_get_contents($pdfname);
		
		//unlink($htmlname);
		unlink($pdfname);
		return $output;
	}
}
?>
